<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>version</key>
    <string>1.0.0</string>
    <key>name</key>
    <string>MiniScript</string>
    <key>scopeName</key>
    <string>source.ms</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numeric</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#function</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#general-functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-methods</string>
      </dict>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>function</key>
      <dict>
        <key>begin</key>
        <string>(?&lt;=function\()</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([^=\),]+)(=[^\),"]+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
                    <key>name</key>
                    <string>variable.parameter.miniscript</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#string</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#numeric</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#constant</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.variable.miniscript</string>
            <key>match</key>
            <string>\b(params|locals|globals|outer)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.language.self.miniscript</string>
            <key>match</key>
            <string>\b(self)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.language.super.miniscript</string>
            <key>match</key>
            <string>\b(super)\b</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.other.attribute.miniscript</string>
            <key>match</key>
            <string>(?&lt;=[^.]\.)\b([a-zA-Z_][\w]*)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.other.miniscript</string>
            <key>match</key>
            <string>\b([A-Z_]+)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.miniscript</string>
            <key>match</key>
            <string>\b([A-Z][\w]*)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.miniscript</string>
            <key>match</key>
            <string>\b([a-z_][\w]*)\b</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line</string>
            <key>begin</key>
            <string>//(?!(include|import))</string>
            <key>end</key>
            <string>\n</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
            <key>match</key>
            <string>(?&lt;![\w\d.])\d+(\.\d+)?([eE]-?\d*)?</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.miniscript</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.block.miniscript</string>
            <key>match</key>
            <string>\b(if|then|end|else|function|in|while|for|from)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.statement.miniscript</string>
            <key>match</key>
            <string>\b(return|continue|break)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.logical.miniscript</string>
            <key>match</key>
            <string>\b(and|or|isa)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.unary.miniscript</string>
            <key>match</key>
            <string>\b(not|new)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.notused.miniscript</string>
            <key>match</key>
            <string>\b(repeat)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.greybel.miniscript</string>
            <key>match</key>
            <string>#(include|import|envar|inject)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.greybel.miniscript</string>
            <key>match</key>
            <string>//(include|import)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.greybel.miniscript</string>
            <key>match</key>
            <string>\b(debugger)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.binary.miniscript</string>
            <key>match</key>
            <string>([\^|\&amp;]|&lt;&lt;|&gt;&gt;&gt;?)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.miniscript</string>
            <key>match</key>
            <string>([+\-*\/%])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.miniscript</string>
            <key>match</key>
            <string>([&lt;&gt;=!]=|[&lt;&gt;])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.miniscript</string>
            <key>match</key>
            <string>([+\-*\/%]?=)</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>name</key>
        <string>constant.language.miniscript</string>
        <key>match</key>
        <string>\b(true|false|null)\b</string>
      </dict>
      <key>type</key>
      <dict>
        <key>name</key>
        <string>support.class.miniscript</string>
        <key>match</key>
        <string>\b(list|map|number|string|funcRef)\b</string>
      </dict>
      <key>general-functions</key>
      <dict>
        <key>name</key>
        <string>support.function.miniscript</string>
        <key>match</key>
        <string>\b(abs|acos|asin|atan|bitAnd|bitOr|bitXor|ceil|char|code|cos|floor|funcRef|hasIndex|hash|indexOf|indexes|insert|join|len|list|log|lower|map|number|pi|pop|print|pull|push|range|refEquals|remove|replace|rnd|round|shuffle|sign|sin|slice|sort|split|sqrt|stackTrace|str|string|sum|tan|time|upper|val|values|version|wait|yield')\b</string>
      </dict>
      <key>type-methods</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.function.miniscript</string>
            <key>match</key>
            <string>\.(remove|push|pop|pull|shuffle|sum|hasIndex|indexOf|sort|join|indexes|len|values)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.miniscript</string>
            <key>match</key>
            <string>\.(remove|push|pop|pull|shuffle|sum|sum|hasIndex|indexOf|indexes|len|values)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>support.function.miniscript</string>
            <key>match</key>
            <string>\.(remove|hasIndex|indexOf|split|replace|trim|indexes|code|len|lower|upper|val|values)\b</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>